package resource

// the env keys
const (
	ENV_FE_ADDR = "ENV_FE_ADDR"

	ENV_FE_PORT = "FE_QUERY_PORT"

	ENV_FE_ELECT_NUMBER = "ELECT_NUMBER"

	COMPONENT_TYPE = "COMPONENT_TYPE"

	FDB_ENDPOINT = "FDB_ENDPOINT"

	NAMESPACE = "NAMESPACE"
)
