FROM golang:1.19 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o doirs-debug cmd/doris-debug/main.go

FROM ubuntu:22.04

WORKDIR /

COPY --from=builder /workspace/doris-debug .


