apiVersion: v1
data:
  instance.conf: |
    {
      "instance_id": "disaggregated-test-cluster3",
      "name": "instance-name",
      "user_id": "test_user",
      "vault": {
        "obj_info": {
          "ak": "test_ak",
          "sk": "test_sk",
          "bucket": "test_bucket",
          "prefix": "test-prefix",
          "endpoint": "cos.ap-beijing.myqcloud.com",
          "external_endpoint": "cos.ap-beijing.myqcloud.com",
          "region": "ap-beijing",
          "provider": "COS",
          "user_id": "test_cluster_user_id"
        }
      }
    }
kind: ConfigMap
metadata:
  name: vault-test