apiVersion: disaggregated.metaservice.doris.com/v1
kind: DorisDisaggregatedMetaService
metadata:
  name: meta-service-test
  namespace: test2
spec:
  fdb:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi
  ms:
    image: selectdb/doris.ms-ubuntu:3.0.0
  recycler:
    image: selectdb/doris.ms-ubuntu:3.0.0
