FROM selectdb/base:latest

RUN ln -s /usr/lib/jvm/jdk-17 /usr/lib/jvm/java

ENV JAVA_HOME=/usr/lib/jvm/java

ENV PATH=$PATH:$JAVA_HOME/bin:/opt/apache-doris/fe/bin

COPY resource/selectdb-cloud-4.0-ubuntu/fe /opt/apache-doris/fe

COPY resource/fe_disaggregated_* /opt/apache-doris

WORKDIR /opt/apache-doris

