FROM selectdb/base:latest

RUN ln -s /usr/lib/jvm/jdk-17 /usr/lib/jvm/java

ENV JAVA_HOME=/usr/lib/jvm/java

ENV PATH=$PATH:$JAVA_HOME/bin:/opt/apache-doris/ms/bin

COPY resource/selectdb-cloud-4.0-ubuntu/ms /opt/apache-doris/ms

COPY resource/ms_disaggregated_* /opt/apache-doris/

WORKDIR /opt/apache-doris

ENTRYPOINT ["bash","/opt/apache-doris/ms_disaggregated_entrypoint.sh"]
