#! /bin/bash

# set the home path

HOME_PATH=$(
  cd "$(dirname "$0")"
  cd ../..
  pwd
)

cd "$HOME_PATH/doris-helm/charts/operator"

# create values.yaml for the parent chart
cat <<EOF >$HOME_PATH/config/operator/operator.yaml
# This file is generated by doris-helm/scripts/operator.sh.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: doris-operator
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: doris
    app.kubernetes.io/component: doris-operator
    app.kubernetes.io/part-of: doris-operator
  name: doris
EOF

helm template -n doris . >>$HOME_PATH/config/operator/operator.yaml
