name: Main

on:
  push:
    tags: "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set output 
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: helm package
        env:
          Version: ${{ steps.vars.outputs.tag }}
        run: cd helm-charts && tar zcf doris-$Version.tgz doris && tar zcf doris-operator-$Version.tgz doris-operator && mv doris-$Version.tgz ../ && mv doris-operator-$Version.tgz ../
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          Version: ${{ steps.vars.outputs.tag }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            doris-*[-]*.*.*.tgz
